pipeline {

    agent {label "ec2"}

    stages{
        stage("Build") {
            steps{

                sh "docker build -t skymer:$BUILD_NUMBER flaskapp/"             
                }
            }

        stage("Push") {

            steps {
                sh """
                  aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 233896446314.dkr.ecr.eu-central-1.amazonaws.com
                  docker tag skymer:$BUILD_NUMBER 233896446314.dkr.ecr.eu-central-1.amazonaws.com/myproject:$BUILD_NUMBER
                  docker push 233896446314.dkr.ecr.eu-central-1.amazonaws.com/myproject:$BUILD_NUMBER
                   """
            }
        }
        
    }
}
