apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}.deploy
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: myapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
      - name: myapp-secret
      containers:
      - name: myapp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          protocol: TCP
        resources:
          requests:
            memory: "200Mi"
            cpu: 0.5
          limits:
            memory: "400Mi"
            cpu: 1.0
