apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  type: LoadBalancer
